In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
import math

# Load data from a CSV file
df = pd.read_csv('dataset.csv')

# Apply label encoding to the 'state' column
label_encoder = LabelEncoder()
df['state'] = label_encoder.fit_transform(df['state'])

df.tail()

,client_id,sex,age,state,risk_profile,a1,a2,a3,a4,a5,...,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20
1166,5146755,1,69,25,4,0.167,0.0,0.165,0.000,0.000,...,0.0,0.095,0.0,0.020,0.0,0.0,0.181,0.000,0.000,0.0
1167,5738347,1,56,11,3,0.034,0.0,0.367,0.000,0.000,...,0.0,0.065,0.0,0.068,0.0,0.0,0.000,0.065,0.049,0.0
1168,8516725,1,64,24,4,0.178,0.0,0.200,0.148,0.046,...,0.0,0.000,0.0,0.055,0.0,0.0,0.023,0.000,0.000,0.0
1169,14240215,1,57,11,3,0.009,0.0,0.000,0.330,0.000,...,0.0,0.000,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0
1170,14326270,0,50,14,3,0.184,0.0,0.621,0.164,0.000,...,0.0,0.000,0.0,0.006,0.0,0.0,0.018,0.000,0.000,0.0


In [2]:
# 'data' contains columns 'sex', 'age', 'state', 'risk_profile'
data = df[['sex', 'age', 'state', 'risk_profile']].values

# 'targets' contains columns 'a1' through 'a20'
targets = df[['a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10', 'a11', 'a12', 'a13', 'a14', 'a15', 'a16', 'a17', 'a18', 'a19', 'a20']].values

# Split the data into training and testing sets
split_ratio = 0.7  # 70% for training, 30% for testing
split_index = int(len(data) * split_ratio)

X_train, X_test = data[:split_index], data[split_index:]
y_train, y_test = targets[:split_index], targets[split_index:]

print('X_train shape =', X_train.shape)
print('y_train shape =', y_train.shape)
print('X_test shape =', X_test.shape)
print('y_test shape =', y_test.shape)

X_train shape = (819, 4)
y_train shape = (819, 20)
X_test shape = (352, 4)
y_test shape = (352, 20)


In [3]:
# Create and train the Multiple Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Display the model parameters
coefficients = model.coef_
intercept = model.intercept_

print("Model Coefficients (Weights):")
print(coefficients)
print("\nModel Intercept (Bias):")
print(intercept)

Model Coefficients (Weights):
[[ 3.82150164e-03 -1.42925893e-03  4.10877156e-04 -1.01008039e-01]
 [ 8.80780466e-04  3.92544126e-05  9.37821548e-05  1.27634378e-03]
 [-1.87792766e-02  5.52954150e-04 -1.32408605e-04 -2.72692276e-02]
 [-4.68678337e-03  5.72967854e-04  4.25622880e-05 -2.82970968e-03]
 [ 1.23129073e-03  1.64683952e-04  5.71018383e-05  1.63348635e-03]
 [ 2.62605933e-04 -2.82042055e-05 -2.66405431e-04  5.77690845e-03]
 [ 1.39327297e-03  4.29225655e-05 -1.42766026e-04  6.84451467e-03]
 [ 4.62371334e-03  2.16407928e-04  7.92322850e-05  1.11077480e-02]
 [ 8.13563613e-03  2.36527076e-04  2.09128427e-04  4.37380268e-02]
 [ 2.38912052e-03 -9.82901759e-05  8.46931002e-05  3.47829901e-02]
 [ 6.64356761e-05  8.28949406e-06 -2.45692225e-05  6.89209034e-04]
 [ 4.17913154e-03 -2.01805762e-04 -1.22639076e-04  2.14673196e-02]
 [ 7.17200167e-04  6.09412619e-06 -6.36134022e-05  3.90673332e-03]
 [ 1.42157119e-03 -9.17433447e-05  8.82083567e-05  6.07836333e-03]
 [ 1.25390716e-03  9.45112359e-0

In [4]:
# Evaluate the model
y_pred = model.predict(X_test)

print('y_test shape =', y_test.shape)
###print('y_test', y_test)
print('y_pred shape =', y_pred.shape)
###print('y_pred', y_pred)

y_test shape = (352, 20)
y_pred shape = (352, 20)


In [5]:
sums = []
for row in y_test:
    sums.append(sum(row))
#print('y_test =', sums)
print("y_test average =", sum(sums)/len(sums))

y_test average = 1.0000227272727267


In [6]:
sums = []
for row in y_pred:
    sums.append(sum(row))
#print('y_pred =', sums)
print("y_pred average =", sum(sums)/len(sums))

y_pred average = 1.0000361953047505


In [7]:
# Calculate RMSE
rmse = math.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error (RMSE) - BEFORE SCALNG: {rmse:.4f}")

Root Mean Squared Error (RMSE) - BEFORE SCALNG: 0.0731


In [8]:
# Scale predictions to get 1 (100%) as a sum of each row
num_rows = len(y_pred)
num_cols = len(y_pred[0])

for row in range(num_rows):
    row_sum = sum(y_pred[row])
    for col in range(num_cols):
        y_pred[row][col] = y_pred[row][col] / row_sum

In [9]:
sums = []
for row in y_pred:
    sums.append(sum(row))
#print('y_pred =', sums)
print("y_pred average =", sum(sums)/len(sums))

y_pred average = 1.0


In [10]:
# Calculate RMSE
rmse = math.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error (RMSE) - AFTER SCALNG: {rmse:.4f}")

Root Mean Squared Error (RMSE) - AFTER SCALNG: 0.0731


In [11]:
#######################################################################################################
#######################################################################################################
#######################################################################################################

In [12]:
X_test

array([[ 1, 41, 33,  4],
       [ 1, 68, 14,  3],
       [ 1, 46, 28,  3],
       ...,
       [ 1, 64, 24,  4],
       [ 1, 57, 11,  3],
       [ 0, 50, 14,  3]], dtype=int64)

In [13]:
y_pred

array([[0.25134338, 0.00612576, 0.15858637, ..., 0.00429706, 0.00160318,
        0.00485845],
       [0.30593757, 0.00412714, 0.20328989, ..., 0.00486256, 0.00341872,
        0.0035359 ],
       [0.34315358, 0.00457676, 0.18928353, ..., 0.00196008, 0.00235346,
        0.00500964],
       ...,
       [0.21476695, 0.00618444, 0.17249247, ..., 0.0055292 , 0.00257143,
        0.00305906],
       [0.32041174, 0.00341386, 0.19759589, ..., 0.00660869, 0.00314418,
        0.00473158],
       [0.32781258, 0.00253961, 0.21209668, ..., 0.00489959, 0.00342239,
        0.00611976]])

In [14]:
for i in range(5):                                   # for i in range(len(y_pred)):
    print(X_test[i], math.sqrt(mean_squared_error(y_test[i], y_pred[i])))

[ 1 41 33  4] 0.044895116777740336
[ 1 68 14  3] 0.09386473121380909
[ 1 46 28  3] 0.040694314686289194
[ 1 72 23  4] 0.09798121008241821
[ 1 36  3  3] 0.05496408274731658


In [15]:
array1 = np.array(X_test)
array2 = np.round(np.array(y_pred), 3)

result_array = np.concatenate((array1, array2), axis=1)

np.set_printoptions(suppress=True)
print(result_array)

np.savetxt('MLR_output.csv', result_array, delimiter=",", fmt='%.3f')

[[ 1.    41.    33.    ...  0.004  0.002  0.005]
 [ 1.    68.    14.    ...  0.005  0.003  0.004]
 [ 1.    46.    28.    ...  0.002  0.002  0.005]
 ...
 [ 1.    64.    24.    ...  0.006  0.003  0.003]
 [ 1.    57.    11.    ...  0.007  0.003  0.005]
 [ 0.    50.    14.    ...  0.005  0.003  0.006]]
